config/routes.rb
Rails.application.routes.draw do
  get "static_profil/profil/:user", to: 'static_profil#profil'
  get "static_welcome/welcome/:hide", to: 'static_welcome#welcome'
  get "static_gossip/gossip/:id", to: 'static_gossip#gossip'


  get "static_contact/contact"
  get "static_team/team"
  get "static_pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :Comments
  has_many :likes
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :comment
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  has_and_belongs_to_many :recipients, class_name: 'User', join_table: 'private_messages_users'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :Comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/static_gossip_controller.rb
class StaticGossipController < ApplicationController
  def gossip
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @gossips = Gossip.all
  end
end

app/controllers/static_team_controller.rb
class StaticTeamController < ApplicationController
  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_contact_helper.rb
module StaticContactHelper
end

app/helpers/static_gossip_helper.rb
module StaticGossipHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/static_profil_helper.rb
module StaticProfilHelper
end

app/helpers/static_team_helper.rb
module StaticTeamHelper
end

app/helpers/static_welcome_helper.rb
module StaticWelcomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/static_gossip/gossip.html.erb
<html>
  <head>
    <title>Créer un potin</title>
    <%= stylesheet_link_tag 'gossip', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <header>
    <div class="menu">

    <%= link_to "Home", static_pages_home_path, class: "lien" %>
    <a class="lien">Gossip</a>
    <%= link_to "Contact", static_contact_contact_path, class: "lien" %>
    <%=  link_to "Team", static_team_team_path, class: "lien" %>

    </div>
  </header>


 <div class="gossiphome">
      <div class="headergossip">
      <div class="imgusertext">
      <%= image_tag "anonyme.png", class: "imguser", alt: "Image Anonyme" %>
      <p class="infogossip"><%= @gossip.user.first_name %></p>
      </div>



      <p>#<%= @gossip.id %> </p>
        </div>
      <p class="textgossip"><%= @gossip.content %></p>
    

</div>





</body>
</html>

app/views/static_pages/home.html.erb
<html>
  <head>
    <title>Créer un potin</title>
    <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <header>
    <div class="menu">

    <%= link_to "Home", static_pages_home_path, class: "lien" %>
    <%= link_to "Contact", static_contact_contact_path, class: "lien" %>
    <%=  link_to "Team", static_team_team_path, class: "lien" %>

    </div>
  </header>

<h2>Liste des Gossips</h2>



    <%  @gossips.each do |gossip| %>
 <div class="gossiphome">
      <div class="headergossip">
      <div class="imgusertext">
      <%= image_tag "anonyme.png", class: "imguser", alt: "Image Anonyme" %>
      <p class="infogossip"><%= gossip.user.first_name %></p>
      </div>



      <p>#<%= gossip.id %> </p>
        </div>
      <p class="textgossip"><%= gossip.content %></p>
      
      <%= link_to "Voir", "/static_gossip/gossip/#{gossip.id}", class: "btn" %>


    <% end %>
  </div>






</body>
</html>

app/views/static_team/team.html.erb
<html>
  <head>
    <title>Créer un potin</title>
    <%= stylesheet_link_tag 'team', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <header>
    <div class="menu">

    <%= link_to "Home", static_pages_home_path, class: "lien" %>
    <%= link_to "Contact", static_contact_contact_path, class: "lien" %>
    <%=  link_to "Team", static_team_team_path, class: "lien" %>

    </div>
  </header>

  

</body>
</html>